### PR TITLE
sci-mathematics/maxima: synchronize changes from main tree

### PR DESCRIPTION
**Pull request by ngg**
Signed-off-by: Gergely Nagy <ngg@ngg.hu>

### CODE REVIEW

**Comment by ngg** [comment]
Maxima is the last package that use python3.8 on my system, I wanted to upgrade that. I found that upstream already had this together with the version bump. I also took the other changes as well, they seem to be reasonable.

**Comment by kiwifb** [comment]
Thank you for the PR. I will study it a little bit before just accepting it. There is just one bit to double check, does sage-9.4 pass its testsuite with that version of maxima? Passing is not completely necessary but I want to be able to catch cases where something is incompatible at the interface level at least.

**Comment by kiwifb** [comment]
I have been slacking on the removal of sage 9.3. I mention it because it is the consumer of maxima-5.44.0. I intend to purge it shortly, along with maxima-5.44.0, which will make that part of the PR irrelevant.

**Comment by ngg** [comment]
I've read the https://sourceforge.net/p/maxima/code/ci/master/tree/changelogs/ChangeLog-5.45.1.md changelog of this version, and it only mentioned a few bug fixes and a revert of a recent gnuplot-related change, there are no interface-level changes.
I did not run the test suite though.

**Comment by kiwifb** [comment]
That will need to be done.

**Comment by kiwifb** [comment]
Tests returned OK on sage-9999 so I'll proceed with merging.

**Comment by kiwifb** [comment]
Hum, I should have taken a better look at your commits. Next time, you should use repoman for commits involving ebuilds.

**Pull request merged**
